config/routes.rb
Rails.application.routes.draw do
  get 'cartola/index'
  root 'cartola#index'

  resources :cartola do
    collection do
      post :import
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cartola_controller.rb
class CartolaController < ApplicationController
  require 'roo'
  require 'spreadsheet'
  require 'roo-xls'

  include CartolaHelper

  def index
  end

  # Summary: Lectura del archivo
  #
  # Params: Archivo que se va a procesar
  # Return: status
  def import
    begin
      movements        = Roo::Excelx.new(params[:file].path, file_warning: :ignore)
      export_file_path = [Rails.root, "public", "cartola_correcta.xls"].join("/")

        if File.file?(export_file_path)
          movements_old = Roo::Spreadsheet.open(export_file_path, extension: :xls)
          if movements.last_row < movements_old.last_row
            especial_movement(movements,movements_old)
          else
            validate_movement(movements,movements_old)
          end
        else
          create_movement(movements)
        end
      return render json: {status: true}
    rescue Exception => e
      puts e
      return false
    end
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartola_helper.rb
module CartolaHelper

  # Summary: Creación de primera cartola
  #
  # Params: Archivo a precesar
  # Return: status
  def create_movement movements
    begin
      header  = movements.row(1)
      book    = Spreadsheet::Workbook.new
      sheet1  = book.create_worksheet :name => 'cartola_correcta'
      count   = 0
      sheet1.row(0).replace header

      (2..movements.last_row).each do |i|
        count = count + 1
        sheet1.row(count).replace movements.row(i)
      end

      export_file_path = [Rails.root, "public", "cartola_correcta.xls"].join("/")
      book.write export_file_path
      send_file export_file_path, :content_type => "application/vnd.ms-excel", :disposition => 'inline'

      return render json: {status: true, header: sheet1}
    rescue Exception => e
      puts e
      return render json: {status: false}
    end
  end

  # Summary: Validación de cartola
  #
  # Params: Archivo precesado anteriormente
  # Return: status
  def validate_movement movements,movements_old
    begin
      book    = Spreadsheet::Workbook.new
      sheet1  = book.create_worksheet :name => 'cartola_correcta'
      count   = 0

      (1..movements.last_row).each do |i|
        (1..movements_old.last_row).each do |r|
          (1..movements.last_row).each do |rw|
            if movements_old.row(r) == movements.row(rw)
              sheet1.row(count).replace movements.row(i)
            else
              if (movements_old.row(r).last.to_i == movements.row(rw).last) and (movements_old.row(r).first != movements.row(r).first)
                sheet1.row(count).replace movements.row(i)
              else
                sheet1.row(count).replace movements.row(i)
              end
            end
          end
        end
        count = count + 1
      end

      export_file_path = [Rails.root, "public", "cartola_correcta.xls"].join("/")
      book.write export_file_path
      send_file export_file_path, :content_type => "application/vnd.ms-excel", :disposition => 'inline'

      return render json: {status: true}
    rescue Exception => e
      puts e
      return render json: {status: false}
    end
  end

    # Summary: Validación de cartola cuando es cambio de mes
  #
  # Params: Archivo precesado anteriormente
  # Return: status
  def especial_movement movements,movements_old
    begin
      book    = Spreadsheet::Workbook.new
      sheet1  = book.create_worksheet :name => 'cartola_correcta'
      count   = 0
      sheet1.row(0).replace movements_old.row(1)

        #Llena sheet con archivo viejo
        (2..movements_old.last_row).each do |i|
          count = count + 1
          sheet1.row(count).replace movements_old.row(i)
        end
        #remplazo repetido viejos por actualizados
        (2..movements.last_row).each do |rw|
          (2..movements_old.last_row).each do |r|
            if (movements.row(rw).last == movements_old.row(r).last) and (movements.row(rw).first != movements_old.row(r).first)
              sheet1.row(r).replace movements.row(rw)
            end
          end
        end
        #Inserta resto de archivo nuevo
        (2..movements.last_row).each do |rw|
          unless movements.row(rw).presence_in sheet1
            count = sheet1.row_count + 1
            sheet1.row(count).replace movements.row(rw)
          else
            puts "existe"
          end
        end
        #Quito los rows nil
        (1..sheet1.row_count).each do |rm|
          unless sheet1.row(rm).present?
             sheet1.delete_row(rm)
          end
        end

      export_file_path = [Rails.root, "public", "cartola_correcta.xls"].join("/")
      book.write export_file_path
      send_file export_file_path, :content_type => "application/vnd.ms-excel", :disposition => 'inline'

      return render json: {status: true}
    rescue Exception => e
      puts e
      return render json: {status: false}
    end
  end
end

app/views/cartola/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Clay</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Importar cartola <span class="sr-only">(current)</span></a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Inciar Sesión</a></li>
        <li><a href="#">Registrarse</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/cartola/index.html.erb
<div class="container" style="margin-top:40px">
  <div class="row">
    <div class="col-sm-6 col-md-4 col-md-offset-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <strong> Importar cartola </strong>
        </div>
        <div class="panel-body">
          <%= form_tag import_cartola_index_path, multipart: true do %>
            <%= file_field_tag :file %>
            <br>
            <%= submit_tag "Importar" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>CartolaClay</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render partial: "cartola/navbar" %>
    <%= yield %>
  </body>
</html>